version: '2'

services:
  vrigin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: virgin
      MYSQL_DATABASE: virgin
      MYSQL_USER: virgin
      MYSQL_PASSWORD: virgin